
* TODO next time try recording at 30fps in obs.

* recording checklist
** OBS
- [ ] studio mode off
- [ ] make sure (settings -> audio -> devices -> mic ) is set to turtle beach
      Refresh in device manager if it doesn't show up.
** j windows
- [ ] preztool should take care af most of this
- [ ] run finished example app
- [ ] then 'c' to clear environment
- [ ] have autohotkey scripts running (tools/viewmat.ahk) if necessary
** microphone
- [ ] green setting


* editing in blender
edit -> preferences -> system -> sequencer cache  = 4096
lower left hand corner in timeline: playback -> top dropdown = av sync

** usage notes
- New / Video Editing
- frame count starts at 1 (not 0)
- "K" cuts clips at the playhead...
- Make sure audio is good volume before you start cutting.
- To batch-edit a property (e.g. volume) on clips later:
  - select them (ctrl-L selects long chains of adjacent clips)
  - set the property on one, then right click the property and "copy to selected"
- ctrl-home / ctrl-end mark current frame as start/end of render

Blender 2.8 seems to have a bug once you cut out some audio and try to remove gaps - suddenly the video and audio fail to line up even with av sync on, and to fix it you have restart blender.

So: I tend to make my cuts, delete the parts i don't want (ums and errs and whatnot) then position the cursor at the start of the video, select all, and press backspace to remove all the gaps at once for a segment of the video. Then I save and restart blender.

actually: selecting the moved strips and toggling mute/unmute (h / alt-h) fixes the problem.
there's already a fix for this in the blender repo https://developer.blender.org/D5391




** transferring video from phone
i use photosync software on both the note9 and the pc
start both, connect via usb port.
select video on phone and hit the transfer (red cycle) button
winds up here (folder will pop up once transfer occurs)
: C:\Users\michal\Pictures\PhotoSync\Samsung SM-N960U1
** converting from phone video
- convert footage to "youtube for hd" avi at 60fps
- make sure render output in blender is 60fps
- and also frame step = 1 (else it'll drop frames)

** rendering to video
- output panel in the properties / scene / output panel
- format: ffmpeg
- container: matroska
- what i did for s1e0
  - video settings:
    - codec: h.264
    - quality: high
    - audio code
  - audio settings:
    - mp3 / bitrate=192

- people complained they couldn't hear the audio, so for s1e1 i used aac with bitrate = 192
- setting output directory to // puts it in same dir as the current file  (d:/videos/j-talks/xxx)
- [ ] youtube recommendations https://support.google.com/youtube/answer/1722171?hl=en
    - container: mp4
    - audio codec: aac-lc stereo; sample rate: 96khz or 48khz
    - video codec: H.264

* publishing on youtube
- switch to tangentstorm account
- add to 'j demos' playlist
- link to gist with finished code

* marketing checklist
- reddit.com/r/apljk
- j programming forum
- twitter

* hardware used
logitech hd 1080p camera
turtle beach streaming mic
  - green setting (cardiod - usually best for streaming)
  - orange setting (hypercardioid - better for noisier room)

https://support.turtlebeach.com/hc/en-us/articles/227345727-Stream-Mic-User-Guide-and-Quick-Start-Guide

not sure about model numbers

* software used
- emacs org-mode for scripts
- OBS Studio
- J
- Blender


* color scheme

title font: kulim park
desktop background: #001824
background colors: 122c3d 003a61 00538a 0071bd 3c90c8
gold bar: html gold = 255 204 0 / ffcc00


* TODO blender color management:
: output -> color management -> transform -> default
prevents blender from changing the colors!


* blender notes
blender: apply transform to bake transforms into the actual geometry
set orign from object -> set origin -> orgin to geometry

* image overlays in the VSE
add image
then add effect -> transform


* animated image overlays in blender (image as plane technique)

- pre-render the raw/cut video
- make a 2d animation scene
- add an empty image and select the the rendered footage
- to hear sound, also add the audio track to the vse

now we can add images and grease pencil to the scene

object mode -> add image -> images as planes
make sure camera is orthographic projection
in the output properties (photo printer icon),
make sure sequencer is *unchecked*, because the
VSE only contains the raw input.

- ortho camera
 - orthographic scale = 1920/1080 -> 1.777

- import image as plane (plugin included with blender)
  - make sure material settings = "shadeless"
    (so the pixels go directly to camera without lighting/shadows)
  - height = 1m for a 1080p image, or set dots/bu=1080

Okay, so now we can composite and animate, but there's no sound.
The sound is coming from the VSE and we're rendering only the composite.

So: to render, add a second scene that renders the first scene plus the original sound.


* green screen color keys

** color gradient technique
https://www.youtube.com/watch?v=clC5lLDn49Q

- add the trackers in tracking view of clip editor
- create a new object to hold the trackers (under track->objects on the right)
- ctrl-click to add a tracker
- then add matte -> keying screen in the compositor node view
